<?xml version="1.0" encoding="utf-8"?><Database Name="SportsStoreDB" Class="StoreDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=laptop-0hsc4h8o;Initial Catalog=SportsStoreDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportsStoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Shoes" Member="Shoes">
    <Type Name="Shoe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShoeType" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsSale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clothing" Member="Clothings">
    <Type Name="Clothing">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClothType" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ClothModel" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsShort" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDreyfit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SportsEquipment" Member="SportsEquipments">
    <Type Name="SportsEquipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sportType" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ModelProduct" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOfTheGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Team_SportsEquipment" Member="Team" ThisKey="IdOfTheGroup" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameOfTheTeam" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Team_SportsEquipment" Member="SportsEquipments" ThisKey="Id" OtherKey="IdOfTheGroup" Type="SportsEquipment" />
    </Type>
  </Table>
</Database>